### ISSUE TITLE
ComputeAndReportContrastsFromSpds needs input and output arguments clarified

### ISSUE THREAD

**Issue by spitschan** [spitschan/SilentSubstitutionToolbox#10]

**Comment by spitschan** [comment]
Fixed in https://github.com/spitschan/SilentSubstitutionToolbox/commit/b79ee722bc1fbe2c2020a58c2546a8334ade3837.

@DavidBrainard: Could you verify that the logic that calculates the the postreceptoral contrasts in line 78 of `ComputeAndReportContrastsFromSpds`. Thanks.

**Comment by DavidBrainard** [comment]
To save me a little hunting, what is a program that calls this routine and illustrates it in action?

**Comment by spitschan** [comment]
E.g. the output of the countrast during spectrum seeking: https://github.com/DavidBrainard/OneLightToolbox/blob/adcd203d81c8e33dfdec81e3aacb04a57b9528b9/OLLibrary/OLCorrectCacheFileOOC.m

**Comment by DavidBrainard** [comment]
DB to check post-receptoral contrast logic.

**Comment by spitschan** [comment]
Flagging this again for @DavidBrainard.

**Comment by DavidBrainard** [comment]
I haven't forgotten.  Will pass through this when I update the validation analysis code for the OneLight project.

**Comment by spitschan** [comment]
Closing this, as superseded by https://github.com/spitschan/SilentSubstitutionToolbox/issues/19
