### ISSUE TITLE
T_energy not quite right, I think

### ISSUE THREAD

**Issue by DavidBrainard** [spitschan/SilentSubstitutionToolbox#28]
Joris and I are looking at SST object makeSpectralSensitivities.

On lines 94-95 we found:

%% Convert to energy fundamentals
T_energy = EnergyToQuanta(obj.S,T_quantalAbsorptionsNormalized')';

So the returned T_energy fundamentals compute absorptions rather than isomerizations.  I don't think there is any reason ever to want absorptions, the biophysically meaningful quantity is isomerizations.  

We are changing this, but posting an issue so you can disagree if there is a reason why really it should be absorptions.  Note that for computation of contrast, which is what we've mostly cared about in the past, this doesn't change anything, since the difference between absorptions and isomerizations is just multiplication by a single scalar representing the quantal efficiency of an absoprtion producing an isomerization.

**Comment by DavidBrainard** [comment]
Made the same change in the other two makeSpectralSensitivities functions.

And added comments that my recommendation is that the STT object not return the absorptions functions, or the normalized quantal fundamentals (see comments in SSTReceptorHuman.

**Comment by DavidBrainard** [comment]
While we're here, we should track back and verify whether pupil diameter is taken into account in the isomerization fundamentals.

**Comment by DavidBrainard** [comment]
Actually, things were even deeper.  The previous energy fundamentals were being computed from normalized absorptions, which makes their units really odd.  Now we are computing from quantalIsomerizations.

**Comment by spitschan** [comment]
Where "previous" means GetHumanPhotoreceptorSS? Presumably this had never 
been a problem b/c contrast is invariant to the scalar.
