### ISSUE TITLE
Stray /SST/lightcalcs folder and functions

### ISSUE THREAD

**Issue by JorisVincent** [spitschan/SilentSubstitutionToolbox#32]
In the SST, under the `SilentSubstitutionToolbox/SST/` folder (where most of the code for the `SSTReceptor` classes lives), there is a folder `lightcalcs` with a few functions. As far as I have been able to check (using a multifile search on the functionnames) these functions are not used by the `SSTReceptor` classes.

I propose we move the `lightcalcs` folder out of the `/SST/` folder (if not out of the SilentSubstitionToolbox alltogether).

**Comment by spitschan** [comment]
I moved it in `SilentSubstitution/LightCalcs`.
