### ISSUE TITLE
ReceptorIsolateDemoOutput

### ISSUE THREAD

**Issue by JorisVincent** [spitschan/SilentSubstitutionToolbox#35]
... contains invalid filenames. This means that at least on Windows (10) using Gitkraken, the repo cannot be cloned. I believe the offender is the character on `[x]` in `[...]OneLight_[x]_Modulation.pdf`

**Comment by spitschan** [comment]
I deleted a bunch of files in 4e72d55fea8954afa7fc3551696e88d4efa57823 with the offending characters. This was caused by casting a numeric as a string in the `ReceptorIsolateDemo` file naming.

**Comment by spitschan** [comment]
@JorisVincent can you check that you can now check out?

**Comment by JorisVincent** [comment]
Yes, works!

**Comment by spitschan** [comment]
Thanks for confirming!

**Comment by spitschan** [comment]
Added a failsafe check to make sure `receptorStrings' is a cell.
